// <auto-generated />
namespace MenBytes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedTwoProperties_USERNAME_And_Pass_IntoUserTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedTwoProperties_USERNAME_And_Pass_IntoUserTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201904200648200_addedTwoProperties_USERNAME_And_Pass_IntoUserTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
